### ISSUE TITLE
Set up newtfire webspace for project

### ISSUE THREAD

**Issue by ebeshero** [beealex/harryPotter#5]
Make this https://harrypotter.newtfire.org

**Comment by beealex** [comment]
Hello Dr. B,

I was checking out the harrypotter.newtfire.org to see if it was made yet and noticed that the link takes me to the "Banksy Project" by Alyssa Argento, Abdual Nadeem, and James Farley. I am not sure if this is a fluke or if it is just because the website wasn't set up yet.

Just thought I would let you know before our meeting at 3:30!
